let julia_path = getEnv("JULIA_PATH")
switch("d", "JULIA_ENABLE_THREADING=1")
switch("clibdir", julia_path & "/lib")
switch("passC", "-fPIC")
switch("passC", "-I" & julia_path & "include/julia")
switch("passL", "-Wl,--export-dynamic")
switch("passL", "-lm")
switch("passL", "-Wl,-rpath," & julia_path & "/lib/")
switch("passL", "-Wl,-rpath," & "/lib/julia")
switch("passL", "-ljulia")
